stages:
  - Unit Tests
  - Integration Tests

# SQL Variables for the WordPress tests
variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql

GI tests:
  image: wordpress
  stage: .pre
  script:
    - echo "Starting Ghost Inspector tests"
    - results=$(curl -s "https://api.ghostinspector.com/v1/suites/5e15e2270756ad297ce9258a/execute/?apiKey=6d95c09df386dbbe2cad26e25b88332d7505015a")
    - if [[ $(jq '.code' <<< $results) != "\"SUCCESS\"" ]]; then
    -   echo "Tests failed to run!"
    -   echo ""
    -   echo "$results"
    -   exit 1
    - fi
    - IFS=$'\n'
    - lines=$(jq '.' <<< $results)
    - passing=1
    - counter=0
    - for line in $lines; do
    -   printf "$counter "
    -   'if [[ "$line" =~ "\"passing\": false," || "$line" =~ "\"passing\": null," ]]; then'
    -     passing=0
    -     printf "***> "
    -   fi
    -   echo "$line"
    -   let counter=counter+1
    - done
    - if [ "$passing" -gt 0 ]; then
    -   echo "Ghost Inspector Integration tests PASSED SUCCESSFULLY!"
    - else
    -   echo "Ghost Inspector Integration tests FAILED!!!"
    -   exit 1
    - fi

  before_script:
    - echo "PreInstall"
    - sudo apt-get -y -qq update
    - sudo apt-get -y install jq curl
    - sudo apt-get -y install php5-cli

# Unit Test Stage

## PHP Unit Tests
PHP 7.3 Unit:
  stage: Unit Tests
  image: edbizarro/gitlab-ci-pipeline-php:7.3-alpine
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer test:unit

PHP 7.2 Unit:
  stage: Unit Tests
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - composer test:unit

## JavaScript Unit Tests
JS Unit Test:
  image: node:latest
  stage: Unit Tests
  script:
    - yarn
    - yarn build
    - yarn test:once

# Integration Test Stage
WP-Integration:
  image: tetraweb/php:7.1
  stage: Integration Tests
  services:
    - mysql:5.6
  script:
    - phpunit --configuration phpunit-integration.xml.dist
  before_script:
    # Install dependencies

    # update the docker
    - apt-get clean
    - apt-get -yqq update

    # install the required packages for the running CI tests
    - apt-get -yqqf install zip unzip subversion mysql-client libmysqlclient-dev --fix-missing

    # PHP extensions
    - docker-php-ext-enable mbstring mcrypt mysqli pdo_mysql intl gd zip bz2

    # Set up WordPress tests
    - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true

    # Install composer, then install with composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-dev
    - php composer.phar global require "phpunit/phpunit:^6"
