stages:
  - Unit Tests
  - Integration Tests

# SQL Variables for the WordPress tests
variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  # to cache both npm modules and Cypress binary we use environment variables
  # to point at the folders we can list as paths in "cache" job settings
  yarn_config_cache: "$CI_PROJECT_DIR/.yarn"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - cache/Cypress
    - node_modules

# this job installs Yarn dependencies and Cypress
install cypress:
  image: cypress/base:10
  stage: .pre

  script:
    - yarn install --frozen-lockfile
    # show where the Cypress test runner binaries are cached
    - $(yarn bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(yarn bin)/cypress cache list
    - $(yarn bin)/cypress verify


# Unit Test Stage

## JavaScript Unit Tests
JS Unit Test:
  image: node:latest
  stage: Unit Tests
  script:
    - yarn
    - yarn build
    - yarn test:once

# Yarn dependencies and Cypress binary should be already installed
cypress-e2e:
  image: cypress/base:10
  stage: Integration Tests
  script:
    - $(yarn bin)/cypress run
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos
    reports:
      junit:
        - results/TEST-*.xml

# Integration Test Stage
WP-Integration:
  image: tetraweb/php:7.1
  stage: Integration Tests
  services:
    - mysql:5.6
  script:
    - phpunit --configuration phpunit-integration.xml.dist
  before_script:
    # Install dependencies

    # update the docker
    - apt-get clean
    - apt-get -yqq update

    # install the required packages for the running CI tests
    - apt-get -yqqf install zip unzip subversion mysql-client libmysqlclient-dev --fix-missing

    # PHP extensions
    - docker-php-ext-enable mbstring mcrypt mysqli pdo_mysql intl gd zip bz2

    # Set up WordPress tests
    - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true

    # Install composer, then install with composer
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-dev
    - php composer.phar global require "phpunit/phpunit:^6"
