name: ZIP

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP dependencies, optimized
        run: composer install --no-dev -o

      - name: Install JS dependencies
        run: yarn

      - name: Build assets for release
        run: yarn build

      # MUST set in package.json to same as tag name before pushing tag
      - name: Set version number 
        run: yarn version:number

      - name: Create build
        run: yarn package

      - name: Create ZIP
        uses: papeloto/action-zip@v1
        with:
          files: build/${GITHUB_REF#refs/*/}/
          recursive: false
          dest: caldera-forms.zip

      - name: Upload ZIP to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: caldera-forms.zip
          tag: ${GITHUB_REF#refs/*/}
